INSERT INTO agent_registry
  (agent_name, display_name, description,
   schedule, enabled)
VALUES
('edgar_intelligence',
  'EDGAR Portfolio Intelligence',
  'REIT and corporate portfolios from SEC filings',
  '0 2 1 * *', true),
('google_places_discovery',
  'Google Places Discovery',
  'Commercial businesses from Google Places',
  '0 3 * * 1', true),
('cms_healthcare',
  'CMS Healthcare Facilities',
  'Medicare/Medicaid facilities',
  '0 4 1 * *', true),
('enrichment',
  'Contact Enrichment',
  'Find contacts, phones, emails for prospects',
  '0 */6 * * *', true),
('noaa_storm_trigger',
  'NOAA Storm Trigger',
  'Real-time hail and wind alerts by territory',
  '0 */4 * * *', false),
('irs_nonprofit',
  'IRS Nonprofit Organizations',
  '1.9M tax-exempt orgs with large facilities',
  '0 6 2 * *', false),
('usda_fsis',
  'USDA Food Processing Facilities',
  'Federally inspected food plants',
  '0 5 1 * *', false),
('florida_assessor',
  'Florida Property Assessor',
  'Statewide commercial parcels from FL DOR',
  '0 2 1 * *', false),
('texas_assessor',
  'Texas County Assessors',
  'Harris, Dallas, Tarrant commercial parcels',
  '0 3 1 * *', false),
('proptracer_scraper',
  'PropTracer Portfolio Scraper',
  'Property ownership data from PropTracer',
  '0 1 * * 0', false),
('sam_gov_contracts',
  'SAM.gov Contract Opportunities',
  'Federal roofing and construction contracts',
  '0 8 * * 1', false),
('nces_schools',
  'NCES School Facilities',
  'Every public school in the US',
  '0 7 3 * *', false),
('gsa_federal',
  'GSA Federal Properties',
  'Federal buildings from GSA FRPP',
  '0 9 4 * *', false),
('pm_company_discovery',
  'PM Company Portfolio Builder',
  'Find PM portfolios via entity matching',
  '0 10 * * 1', false);
